#!/bin/bash

# Script generated by ChatGPT 4o

# Check if the number of lines is provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 <number_of_lines> <output_file>"
    exit 1
fi

num_lines=$1
output_file=$2

# Function to generate a random string of a given length
generate_random_string() {
    local length=$1
    od -vAn -N"$length" -tu1 /dev/urandom | tr -cd 'a-zA-Z0-9' | head -c "$length"
}

# Clear the output file if it exists
> "$output_file"

# Generate the specified number of lines
for ((i = 0; i < num_lines; i++)); do
    random_string=$(generate_random_string $((RANDOM % 1000 + 1)))
    echo -ne "$random_string\0\n" >> "$output_file" # Add a null terminator and newline
done

echo "Generated $num_lines lines of random null-terminated strings in $output_file"

